name = "next-star"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

# Production environment
[env.production]
name = "next-star"

